name: Deploy Calculator App

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          
      - name: Build Electron App
        run: |
          cd src
          npm install
          npm run build
          
      - name: Deploy Infrastructure
        run: |
          cd terraform
          terraform init
          terraform workspace select ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
          terraform apply -auto-approve -var-file="terraform.tfvars.${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}"